includes:
    - pb-client.yaml


pipelines:
    sync-client:
        get-changes:
            chained_consumers:
                - get-jr-changes
                - ship-jr-changes:
                    method: apply_changes
                    input_path: changes
                - empty-jr-audit-tables


ticks:
    interval:
        get-changes:
            interval: 3
            processor:
                provider: pipeline.sync-client.get-changes
